# Generated by Django 3.2 on 2021-05-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210506_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catproducto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.IntegerField(default=0),
        ),
    ]
