# Generated by Django 3.2 on 2021-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210503_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
