# Generated by Django 3.2 on 2021-05-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
